### PR TITLE
added the first blog

### PR DESCRIPTION
**Pull request by codekhal**
I have to update the Linkedin profile of Aditi. I will let you know when to merge.

### CODE REVIEW

**Comment by codekhal** [comment]
@ramantehlan Kindly review if any bugs remain in the blog before merging it!

**Comment by codekhal** [comment]
You may kindly review and merge now :)

**Review by ramantehlan — APPROVED** [review]

**Comment by ramantehlan** [comment]
I feel the title is too long, for now, I will post it. we will update it if there will be any change. 

Thank you for your contribution. :+1:

**Comment by codekhal** [comment]
Okay, I will update that!

**Comment by codekhal** [comment]
Kindly review! @ramantehlan

**Pull request merged**
